#!/bin/bash

JOLOKIA_URL=${1}

THREADS=`curl -X POST -s ${JOLOKIA_URL}   -H 'Content-Type: application/json' -d '{"type": "read","mbean": "org.glassfish.grizzly:pp=/gmbal-root/HttpServer[HttpServer]/NetworkListener[NetworkListener[grizzly]]/TCPNIOTransport[Transport],type=ThreadPool,name=Grizzly-worker","attribute": "thread-pool-busy-thread-count"}' | jq '.["value"]'`

echo "Jolokia Threads OK | Thread=${THREADS};;;"
